[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#EFF1F5"
foreground = "#4C4F69"
dim_foreground = "#4C4F69"
bright_foreground = "#4C4F69"

[colors.cursor]
text = "#EFF1F5"
cursor = "#DC8A78"

[colors.vi_mode_cursor]
text = "#EFF1F5"
cursor = "#7287FD"

[colors.search.matches]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.search.focused_match]
foreground = "#EFF1F5"
background = "#40A02B"

[colors.footer_bar]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.hints.start]
foreground = "#EFF1F5"
background = "#DF8E1D"

[colors.hints.end]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.selection]
text = "#EFF1F5"
background = "#DC8A78"

[colors.normal]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[colors.bright]
black = "#6C6F85"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#BCC0CC"

[colors.dim]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[[colors.indexed_colors]]
index = 16
color = "#FE640B"

[[colors.indexed_colors]]
index = 17
color = "#DC8A78"

[env]
TERM = "alacritty"

[font]
size = 14

# [font.bold]
# # family = "GeistMono Nerd Font"
# family = "JetBrainsMonoNL Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# # family = "GeistMono Nerd Font"
# family = "JetBrainsMonoNL Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# # family = "GeistMono Nerd Font"
# family = "JetBrainsMonoNL Nerd Font"
# style = "Italic"

[font.normal]
# family = "GeistMono Nerd Font Mono"
family = "GohuFont uni14 Nerd Font"
# family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Back", mods = "Super", chars = "\u0015"},
]

[window]
decorations = "full"
dynamic_title = false
title = "padulcritty"

[window.padding]
x = 8
y = 8
