[colors]
draw_bold_text_with_bright_colors = true

# xterm colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

[env]
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "GohuFont uni14 Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Back", mods = "Super", chars = "\u0015"},
]

[window]
decorations = "none"
dynamic_title = false
# title = "padulcritty"

[window.padding]
x = 8
y = 8
