[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#8a8980"
blue = "#6693bf"
cyan = "#5e857a"
green = "#6e915f"
magenta = "#624c83"
red = "#d7474b"
white = "#43436c"
yellow = "#836f4a"

[colors.normal]
black = "#1F1F28"
blue = "#4d699b"
cyan = "#597b75"
green = "#6f894e"
magenta = "#b35b79"
red = "#c84053"
white = "#545464"
yellow = "#77713f"

[colors.primary]
background = "#f2ecbc"
foreground = "#545464"
dim_foreground = "#545464"
bright_foreground = "#545464"

[[colors.indexed_colors]]
index = 16
color = "#e98a00"

[[colors.indexed_colors]]
index = 17
color = "#e82424"

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[keyboard]
bindings = [
  { key = "Back", mods = "Super", chars = "\u0015"},
]

[window]
decorations = "full"
dynamic_title = false
title = "padulcritty"

[window.padding]
x = 4
y = 12
