[tools]
go = "latest"
kotlin = "1.9.22"
ruby = "2.7.5"
flutter = "3.22.3"
bun = "latest"
java = "21"
node = "20"
python = "3.10"
cmake = "4.0.2"

[settings]
idiomatic_version_file_enable_tools = ["node"]
