[tools]
go = "latest"
kotlin = "1.9.23"
ruby = "3.4.7"
flutter = "3.38"
java = "21"
node = "20"
python = "3.14"
odin = "latest"
leiningen = "2.12"

[settings]
idiomatic_version_file_enable_tools = ["node"]
