#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label work
yabai -m space 3 --label mail
yabai -m space 4 --label personal

# window rules
yabai -m rule --add app="^Emacs$" space=web
yabai -m rule --add app="^Helium$" space=web
yabai -m rule --add app="^Spark Desktop$" space=mail
yabai -m rule --add app="^Ghostty$" space=work
yabai -m rule --add app="^Bruno$" space=work
yabai -m rule --add app="^IntelliJ IDEA$" space=work
yabai -m rule --add app="^OrbStack$" space=work
yabai -m rule --add app="^OBS$" space=mail
yabai -m rule --add app="^(Calculator|System Settings|Archive Utility|OnyX)$" manage=off

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_animation_duration    0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   8

echo "conf loaded"
