leader = ','
comment_types = [
  {  id = 'question(non-blocking)', label = 'question(non-blocking)', definition = 'ask for clarification', color = 'yellow' },
  {  id = 'suggestion(non-blocking)', label = 'suggestion(non-blocking)', definition = 'possible non-blocking improvements, resolve if needed', color = 'magenta' },
  {  id = 'suggestion(blocking)', label = 'suggestion(blocking)', definition = 'possible blocking issue', color = 'red' },
]
